# Github action for releasing the binaries
name: Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install

      - name: Check linting
        run: |
          npm run-script lint
  
      - name: Check format
        run: |
          npm run-script check-format
  compile:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
        - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: |
            npm install
        - name: Build
          run: | 
            npm run-script package
  ui-test:
      needs: [compile, format]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
        - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: |
            npm install
        - name: Ui test
          run: | 
            npm run-script docker-build-ui-test
            npm run-script docker-start-ui-test
        - uses: actions/upload-artifact@v4
          if: ${{ failure() }}
          with:
            # Name of the artifact to upload.
            # Optional. Default is 'artifact'
            name: upload-screenshot

            # A file, directory or wildcard pattern that describes what to upload
            # Required.
            path: test-resources/screenshots/