name: Compliance

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Plumber
      uses: outscale/.github/pipeline-compliance@82a9889d98a317d5ef844026429dbc8827f306f2 # v1.2.1
      with:
        plumber-threshold: 100
        github-token: ${{ secrets.PLUMBER_TOKEN }}
