name: Github sanity scanner

on:
  pull_request:
    branches: [ main ]

jobs:
  github-sanity-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Github sanity scanner
      uses: outscale/github-sanity-scan@380a9927b4be45d9c4f6f66a4e8dfd7cf7b18513 # main
      with:
        no-pull-request-target: true
